const {
  LANGUAGE_COLORS,
  normalizeFilePath
} = require("./defaults");
const {
  bytesToSize,
  escapeAttr,
  escapeHtml,
  pluralize,
  stableHash
} = require("./utils");
const { formatMarkdown } = require("./analyzer");
const { SAMPLE_PROJECTS } = require("./samples");

function renderHtml(report) {
  // Ensure we don't leak local paths or mutate input graph nodes
  const safeReport = {
    ...report,
    root: undefined,
    graph: {
      nodes: (report.graph && report.graph.nodes) ? report.graph.nodes.map((n) => ({ ...n })) : [],
      edges: (report.graph && report.graph.edges) ? report.graph.edges.map((e) => ({ ...e })) : []
    }
  };

  const payload = JSON.stringify(safeReport).replace(/</g, "\\u003c");
  const markdownPayload = JSON.stringify(formatMarkdown(safeReport)).replace(/</g, "\\u003c");
  const languagePayload = JSON.stringify(LANGUAGE_COLORS).replace(/</g, "\\u003c");
  const samplesPayload = JSON.stringify(SAMPLE_PROJECTS).replace(/</g, "\\u003c");

  return `<!doctype html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(report.title)} · StackSketch</title>
  <meta name="description" content="Local-first architectural dependency map and codebase intelligence report generated by StackSketch.">
  <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 rx=%2224%22 fill=%22%234f46e5%22/><path d=%22M28 32h44v12H28zm0 18h32v12H28zm0 18h44v12H28z%22 fill=%22%23ffffff%22/></svg>">
  <style>
    :root {
      color-scheme: dark;
      --bg: #090d16;
      --surface: #0f172a;
      --surface-subtle: #141e33;
      --surface-card: #131d31;
      --surface-elevated: #1e293b;
      --surface-border: rgba(255, 255, 255, 0.08);
      --border-subtle: rgba(255, 255, 255, 0.05);
      --border-accent: rgba(99, 102, 241, 0.45);
      --text: #f1f5f9;
      --text-muted: #94a3b8;
      --text-subtle: #64748b;
      --accent: #6366f1;
      --accent-hover: #4f46e5;
      --accent-soft: rgba(99, 102, 241, 0.12);
      --accent-text: #c7d2fe;
      --success: #10b981;
      --warning: #f59e0b;
      --danger: #f43f5e;
      --info: #0ea5e9;
      --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.25);
      --shadow-md: 0 4px 16px rgba(0, 0, 0, 0.35);
      --shadow-lg: 0 12px 32px rgba(0, 0, 0, 0.45);
      --radius-sm: 6px;
      --radius-md: 10px;
      --radius-lg: 14px;
      --font-sans: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      --font-mono: ui-monospace, "SFMono-Regular", Menlo, Monaco, Consolas, "Liberation Mono", monospace;
    }

    [data-theme="light"] {
      color-scheme: light;
      --bg: #f8fafc;
      --surface: #ffffff;
      --surface-subtle: #f1f5f9;
      --surface-card: #ffffff;
      --surface-elevated: #f8fafc;
      --surface-border: rgba(0, 0, 0, 0.08);
      --border-subtle: rgba(0, 0, 0, 0.05);
      --border-accent: rgba(79, 70, 229, 0.45);
      --text: #0f172a;
      --text-muted: #475569;
      --text-subtle: #94a3b8;
      --accent: #4f46e5;
      --accent-hover: #4338ca;
      --accent-soft: rgba(79, 70, 229, 0.08);
      --accent-text: #3730a3;
      --success: #059669;
      --warning: #d97706;
      --danger: #e11d48;
      --info: #0284c7;
      --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.04);
      --shadow-md: 0 4px 14px rgba(0, 0, 0, 0.06);
      --shadow-lg: 0 12px 28px rgba(0, 0, 0, 0.09);
    }

    * { box-sizing: border-box; margin: 0; padding: 0; }

    html, body {
      width: 100%;
      height: 100%;
      overflow: hidden;
      background: var(--bg);
      color: var(--text);
      font-family: var(--font-sans);
      font-size: 14px;
      line-height: 1.5;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }

    button, input, select {
      font: inherit;
      color: inherit;
    }

    button {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 6px;
      padding: 7px 14px;
      font-size: 13px;
      font-weight: 500;
      border-radius: var(--radius-md);
      border: 1px solid var(--surface-border);
      background: var(--surface);
      color: var(--text);
      cursor: pointer;
      white-space: nowrap;
      transition: all 0.15s ease;
      user-select: none;
    }

    button:hover {
      background: var(--surface-subtle);
      border-color: var(--text-subtle);
      transform: translateY(-0.5px);
    }

    button:active {
      transform: translateY(0);
    }

    button.primary {
      background: var(--accent);
      border-color: var(--accent);
      color: #ffffff;
      font-weight: 600;
    }

    button.primary:hover {
      background: var(--accent-hover);
      border-color: var(--accent-hover);
    }

    button.ghost {
      background: transparent;
      border-color: transparent;
    }

    button.ghost:hover {
      background: var(--surface-subtle);
      border-color: var(--surface-border);
    }

    button.sm {
      padding: 5px 10px;
      font-size: 12px;
      border-radius: var(--radius-sm);
    }

    input[type="search"], input[type="text"], select {
      width: 100%;
      padding: 8px 12px;
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-md);
      color: var(--text);
      font-size: 13px;
      outline: none;
      transition: border-color 0.15s, box-shadow 0.15s;
    }

    input[type="search"]:focus, select:focus {
      border-color: var(--accent);
      box-shadow: 0 0 0 3px var(--accent-soft);
    }

    /* Layout structure */
    .app {
      display: grid;
      grid-template-rows: 56px 1fr;
      height: 100vh;
      width: 100vw;
      background: var(--bg);
    }

    /* Top navigation bar */
    .topbar {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      padding: 0 16px;
      background: var(--surface);
      border-bottom: 1px solid var(--surface-border);
      z-index: 20;
    }

    .brand {
      display: flex;
      align-items: center;
      gap: 12px;
      min-width: 0;
    }

    .logo {
      width: 32px;
      height: 32px;
      border-radius: var(--radius-md);
      background: var(--accent);
      color: #ffffff;
      display: grid;
      place-items: center;
      font-weight: 700;
      font-size: 16px;
      flex-shrink: 0;
      box-shadow: var(--shadow-sm);
    }

    .brand-meta {
      min-width: 0;
    }

    .brand-title {
      font-size: 15px;
      font-weight: 600;
      letter-spacing: -0.01em;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .brand-subtitle {
      font-size: 11px;
      color: var(--text-muted);
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    /* View Switcher Tabs */
    .nav-tabs {
      display: inline-flex;
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-md);
      padding: 3px;
      gap: 2px;
    }

    .nav-tab {
      padding: 5px 12px;
      font-size: 12px;
      font-weight: 500;
      border-radius: var(--radius-sm);
      border: none;
      background: transparent;
      color: var(--text-muted);
      cursor: pointer;
      transition: all 0.12s;
    }

    .nav-tab:hover {
      color: var(--text);
      background: transparent;
      transform: none;
    }

    .nav-tab.active {
      background: var(--surface);
      color: var(--text);
      font-weight: 600;
      box-shadow: var(--shadow-sm);
    }

    .top-actions {
      display: flex;
      align-items: center;
      gap: 8px;
    }

    /* Workspace 3-column layout */
    .workspace {
      display: grid;
      grid-template-columns: 330px 1fr 350px;
      min-height: 0;
      height: 100%;
      overflow: hidden;
    }

    .panel {
      overflow-y: auto;
      overflow-x: hidden;
      background: var(--surface);
      border-right: 1px solid var(--surface-border);
    }

    .panel.sidebar {
      padding: 16px;
      display: flex;
      flex-direction: column;
      gap: 20px;
    }

    .panel.inspector {
      border-right: none;
      border-left: 1px solid var(--surface-border);
      padding: 16px;
    }

    /* Section typography & widgets */
    .section {
      display: flex;
      flex-direction: column;
      gap: 10px;
    }

    .section-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 8px;
    }

    .section-title {
      font-size: 11px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--text-muted);
    }

    .badge-counter {
      font-size: 11px;
      padding: 2px 7px;
      border-radius: 999px;
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
      color: var(--text-muted);
      font-family: var(--font-mono);
    }

    /* Metrics Grid */
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 8px;
    }

    .metric-card {
      padding: 10px 12px;
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-md);
      display: flex;
      flex-direction: column;
      gap: 2px;
    }

    .metric-card strong {
      font-size: 18px;
      font-weight: 700;
      letter-spacing: -0.02em;
      color: var(--text);
      font-family: var(--font-sans);
    }

    .metric-card span {
      font-size: 11px;
      color: var(--text-muted);
    }

    /* Legend and chips */
    .legend {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 6px;
    }

    .legend-item {
      display: flex;
      align-items: center;
      gap: 7px;
      font-size: 12px;
      color: var(--text-muted);
      padding: 4px 6px;
      border-radius: var(--radius-sm);
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
    }

    .legend-dot {
      width: 8px;
      height: 8px;
      border-radius: 999px;
      flex-shrink: 0;
    }

    .legend-item b {
      color: var(--text);
      font-weight: 500;
    }

    .chips {
      display: flex;
      flex-wrap: wrap;
      gap: 6px;
    }

    .chip {
      display: inline-flex;
      align-items: center;
      gap: 5px;
      padding: 4px 9px;
      font-size: 11px;
      border-radius: var(--radius-sm);
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
      color: var(--text-muted);
    }

    .chip b {
      color: var(--text);
      font-weight: 600;
    }

    .filters-list {
      display: flex;
      flex-direction: column;
      gap: 4px;
      max-height: 180px;
      overflow-y: auto;
      padding-right: 4px;
    }

    .check-item {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 8px;
      padding: 6px 10px;
      font-size: 12px;
      border-radius: var(--radius-sm);
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
      cursor: pointer;
      transition: background 0.12s;
    }

    .check-item:hover {
      background: var(--surface-elevated);
    }

    .check-item-left {
      display: flex;
      align-items: center;
      gap: 8px;
    }

    .check-item input[type="checkbox"] {
      width: 14px;
      height: 14px;
      accent-color: var(--accent);
      cursor: pointer;
    }

    /* Tables */
    .file-table-wrapper {
      max-height: 240px;
      overflow: auto;
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-md);
    }

    .file-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 12px;
      text-align: left;
    }

    .file-table th {
      position: sticky;
      top: 0;
      background: var(--surface-elevated);
      color: var(--text-muted);
      font-weight: 600;
      font-size: 11px;
      padding: 8px 10px;
      border-bottom: 1px solid var(--surface-border);
      z-index: 2;
    }

    .file-table td {
      padding: 6px 10px;
      border-bottom: 1px solid var(--border-subtle);
      color: var(--text);
    }

    .file-table tr:hover td {
      background: var(--surface-subtle);
      cursor: pointer;
    }

    .file-table code {
      font-family: var(--font-mono);
      font-size: 11px;
      color: var(--accent-text);
      display: block;
      max-width: 140px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    .file-table td.num {
      text-align: right;
      font-family: var(--font-mono);
      font-size: 11px;
      color: var(--text-muted);
    }

    /* Directory Tree */
    .tree-wrapper {
      max-height: 220px;
      overflow: auto;
      padding: 8px 10px;
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-md);
      font-family: var(--font-mono);
      font-size: 11px;
    }

    .tree {
      display: flex;
      flex-direction: column;
      gap: 1px;
    }

    .tree-folder > summary {
      display: flex;
      align-items: center;
      gap: 6px;
      padding: 3px 4px;
      border-radius: var(--radius-sm);
      cursor: pointer;
      user-select: none;
      list-style: none;
    }

    .tree-folder > summary::-webkit-details-marker {
      display: none;
    }

    .tree-folder > summary:hover {
      background: var(--surface-elevated);
    }

    .tree-twisty {
      width: 0;
      height: 0;
      border-left: 4px solid var(--text-subtle);
      border-top: 4px solid transparent;
      border-bottom: 4px solid transparent;
      flex-shrink: 0;
      transition: transform 0.12s ease;
    }

    .tree-folder[open] > summary .tree-twisty {
      transform: rotate(90deg);
    }

    .tree-icon {
      width: 8px;
      height: 8px;
      border-radius: 999px;
      flex-shrink: 0;
      background: var(--text-subtle);
    }

    .tree-icon.folder {
      background: var(--accent);
    }

    .tree-name {
      font-size: 11px;
      color: var(--text-muted);
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .tree-folder > summary .tree-name {
      color: var(--text);
      font-weight: 500;
    }

    .tree-count {
      margin-left: auto;
      font-size: 10px;
      color: var(--text-subtle);
      font-family: var(--font-mono);
      flex-shrink: 0;
    }

    .tree-file {
      display: flex;
      align-items: center;
      gap: 6px;
      padding: 3px 4px 3px 18px;
      border-radius: var(--radius-sm);
      cursor: pointer;
    }

    .tree-file:hover {
      background: var(--surface-elevated);
    }

    .tree-file .tree-name {
      color: var(--accent-text);
    }

    .tree-children {
      margin-left: 8px;
      padding-left: 8px;
      border-left: 1px solid var(--surface-border);
      display: flex;
      flex-direction: column;
      gap: 1px;
    }

    .tree-more {
      padding: 2px 4px 2px 18px;
      font-size: 10px;
      font-style: italic;
      color: var(--text-subtle);
    }

    .tree-note {
      margin-top: 8px;
      font-size: 10px;
      line-height: 1.4;
      color: var(--warning);
    }

    /* Stage Area & Canvas */
    .stage {
      display: flex;
      flex-direction: column;
      min-width: 0;
      height: 100%;
      position: relative;
      background: var(--bg);
      overflow: hidden;
    }

    .canvas-panel {
      width: 100%;
      height: 100%;
      position: relative;
      overflow: hidden;
    }

    .canvas-toolbar {
      position: absolute;
      top: 14px;
      left: 14px;
      right: 14px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
      pointer-events: none;
      z-index: 10;
    }

    .canvas-toolbar > * {
      pointer-events: auto;
    }

    .status-pill {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 6px 12px;
      font-size: 12px;
      font-family: var(--font-mono);
      border-radius: 999px;
      background: var(--surface);
      border: 1px solid var(--surface-border);
      color: var(--text-muted);
      box-shadow: var(--shadow-sm);
    }

    .canvas-controls {
      display: flex;
      align-items: center;
      gap: 6px;
      background: var(--surface);
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-md);
      padding: 4px;
      box-shadow: var(--shadow-sm);
    }

    .canvas-controls .tool-btn {
      padding: 6px 9px;
      font-size: 12px;
      border: none;
      background: transparent;
      color: var(--text-muted);
      border-radius: var(--radius-sm);
    }

    .canvas-controls .tool-btn:hover {
      background: var(--surface-subtle);
      color: var(--text);
      transform: none;
    }

    .canvas-controls .toggle-label {
      display: flex;
      align-items: center;
      gap: 5px;
      padding: 4px 8px;
      font-size: 12px;
      color: var(--text-muted);
      cursor: pointer;
      user-select: none;
    }

    .canvas-controls .toggle-label input {
      accent-color: var(--accent);
    }

    .canvas-controls input[type="range"] {
      width: 100px;
      accent-color: var(--accent);
      cursor: pointer;
    }

    canvas {
      width: 100%;
      height: 100%;
      display: block;
      cursor: grab;
    }

    canvas.dragging {
      cursor: grabbing;
    }

    /* Views: Treemap, Matrix, Insights */
    .view-container {
      display: none;
      width: 100%;
      height: 100%;
      overflow: auto;
      padding: 24px;
    }

    .view-container.active {
      display: block;
    }

    /* Inspector Card */
    .inspector-card {
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    .inspector-title {
      font-size: 16px;
      font-weight: 600;
      word-break: break-all;
      letter-spacing: -0.01em;
      line-height: 1.3;
    }

    .inspector-desc {
      font-size: 13px;
      color: var(--text-muted);
      line-height: 1.5;
    }

    .kv-grid {
      display: grid;
      grid-template-columns: 1fr auto;
      gap: 8px 12px;
      padding: 12px;
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-md);
      font-size: 12px;
    }

    .kv-grid dt {
      color: var(--text-muted);
    }

    .kv-grid dd {
      color: var(--text);
      font-family: var(--font-mono);
      font-weight: 500;
      text-align: right;
    }

    .tag-cloud {
      display: flex;
      flex-wrap: wrap;
      gap: 6px;
      max-height: 160px;
      overflow-y: auto;
    }

    .tag {
      font-size: 11px;
      font-family: var(--font-mono);
      padding: 3px 8px;
      background: var(--surface-subtle);
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-sm);
      color: var(--text);
      max-width: 100%;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }

    .tag.highlight {
      background: var(--accent-soft);
      border-color: var(--border-accent);
      color: var(--accent-text);
    }

    /* Modal dialog */
    .modal-overlay {
      position: fixed;
      inset: 0;
      background: rgba(0, 0, 0, 0.65);
      backdrop-filter: blur(4px);
      z-index: 100;
      display: none;
      place-items: center;
      padding: 20px;
    }

    .modal-overlay.open {
      display: grid;
    }

    .modal-content {
      width: 100%;
      max-width: 520px;
      background: var(--surface);
      border: 1px solid var(--surface-border);
      border-radius: var(--radius-lg);
      padding: 24px;
      box-shadow: var(--shadow-lg);
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    .modal-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
    }

    .modal-header h3 {
      font-size: 17px;
      font-weight: 600;
    }

    /* Toast Notification */
    .toast {
      position: fixed;
      bottom: 24px;
      right: 24px;
      padding: 10px 18px;
      border-radius: var(--radius-md);
      background: var(--surface-elevated);
      color: var(--text);
      border: 1px solid var(--surface-border);
      box-shadow: var(--shadow-lg);
      font-size: 13px;
      font-weight: 500;
      z-index: 200;
      opacity: 0;
      transform: translateY(10px);
      transition: all 0.2s ease;
      pointer-events: none;
    }

    .toast.show {
      opacity: 1;
      transform: translateY(0);
    }

    /* Responsive */
    @media (max-width: 1100px) {
      .workspace {
        grid-template-columns: 280px 1fr;
      }
      .panel.inspector {
        display: none;
      }
    }

    @media (max-width: 800px) {
      .topbar {
        flex-wrap: wrap;
        height: auto;
        padding: 10px 16px;
      }
      .workspace {
        grid-template-columns: 1fr;
      }
      .panel.sidebar {
        display: none;
      }
    }
  </style>
</head>
<body>
  <div class="app">
    <!-- Topbar -->
    <header class="topbar">
      <div class="brand">
        <div class="logo">S</div>
        <div class="brand-meta">
          <h1 class="brand-title">${escapeHtml(report.title)}</h1>
          <div class="brand-subtitle">StackSketch · Zero-Config Architecture Intelligence</div>
        </div>
      </div>

      <!-- Navigation Tabs -->
      <nav class="nav-tabs" aria-label="View Switcher">
        <button class="nav-tab active" data-view="graph">Topology Graph</button>
        <button class="nav-tab" data-view="matrix">File Matrix</button>
        <button class="nav-tab" data-view="insights">Architecture Insights</button>
      </nav>

      <!-- Global Actions -->
      <div class="top-actions">
        <!-- Sample selector -->
        <select id="projectSelector" style="width: auto; padding: 5px 10px; font-size: 12px;">
          <option value="local">Live Codebase</option>
        </select>

        <button id="rescanBtn" title="Rescan repository from disk">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67"/></svg>
          Scan
        </button>

        <!-- Export Dropdown -->
        <select id="exportSelector" style="width: auto; padding: 5px 10px; font-size: 12px;">
          <option value="" disabled selected>Export...</option>
          <option value="svg">Vector SVG</option>
          <option value="png">PNG Image</option>
          <option value="markdown">Copy Markdown</option>
          <option value="json">Download JSON</option>
        </select>

        <button id="themeToggle" class="ghost" title="Toggle theme (Light / Dark)">
          <svg id="themeIcon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></svg>
        </button>
      </div>
    </header>

    <!-- Main Workspace -->
    <main class="workspace">
      <!-- Left Panel: Sidebar -->
      <aside class="panel sidebar">
        <div class="section">
          <div class="section-header">
            <span class="section-title">Search Codebase</span>
            <span class="badge-counter" id="matchCounter">${report.summary.scannedFiles} nodes</span>
          </div>
          <input id="search" type="search" placeholder="Filter files, imports, symbols... (Ctrl+K)" autocomplete="off">
        </div>

        <div class="section">
          <div class="section-header">
            <span class="section-title">Summary Metrics</span>
            <span class="badge-counter">${escapeHtml(report.humanSummary.files)} files</span>
          </div>
          <div class="stats-grid">
            <div class="metric-card">
              <strong>${escapeHtml(report.humanSummary.sourceFiles)}</strong>
              <span>Source Files</span>
            </div>
            <div class="metric-card">
              <strong>${escapeHtml(report.humanSummary.lines)}</strong>
              <span>Code Lines</span>
            </div>
            <div class="metric-card">
              <strong>${escapeHtml(report.humanSummary.edges)}</strong>
              <span>Local Edges</span>
            </div>
            <div class="metric-card">
              <strong>${escapeHtml(report.humanSummary.size)}</strong>
              <span>Project Size</span>
            </div>
          </div>
        </div>

        <div class="section">
          <div class="section-header">
            <span class="section-title">Languages</span>
            <button class="ghost sm" id="toggleAllLangs" title="Toggle all languages">All</button>
          </div>
          <div class="filters-list" id="languageFilters">
            ${renderLanguageFilters(report)}
          </div>
        </div>

        <div class="section">
          <div class="section-header">
            <span class="section-title">Frameworks</span>
          </div>
          <div class="chips">${renderFrameworks(report)}</div>
        </div>

        <div class="section">
          <div class="section-header">
            <span class="section-title">Scan Scope</span>
          </div>
          <div class="chips">${renderScanScope(report)}</div>
        </div>

        <div class="section">
          <div class="section-header">
            <span class="section-title">Top Files by LOC</span>
          </div>
          <div class="file-table-wrapper">
            <table class="file-table">
              <thead>
                <tr>
                  <th>Path</th>
                  <th style="text-align:right">LOC</th>
                  <th style="text-align:right">Deps</th>
                </tr>
              </thead>
              <tbody id="topFilesTableBody">
                ${renderTopFiles(report)}
              </tbody>
            </table>
          </div>
        </div>

        <div class="section">
          <div class="section-header">
            <span class="section-title">Directory Structure</span>
            <button class="ghost sm" id="expandAllTree" title="Expand or collapse all folders">Expand</button>
          </div>
          <div class="tree-wrapper">
            <div class="tree" id="directoryTree"></div>
            <div class="tree-note" id="treeNote" style="display:none"></div>
          </div>
        </div>
      </aside>

      <!-- Center Stage -->
      <section class="stage">
        <!-- View 1: Canvas Graph -->
        <div class="canvas-panel view-container active" id="view-graph">
          <div class="canvas-toolbar">
            <div class="status-pill" id="status">Scanning architecture graph...</div>
            <div class="canvas-controls">
              <button class="tool-btn" id="zoomIn" title="Zoom in">+</button>
              <button class="tool-btn" id="zoomOut" title="Zoom out">-</button>
              <input type="range" id="zoomSlider" min="0.05" max="4" step="0.05" value="1" title="Zoom level" aria-label="Zoom level">
              <button class="tool-btn" id="fit" title="Fit to viewport">Fit</button>
              <button class="tool-btn" id="reset" title="Reset layout">Reset</button>
              <span style="width:1px;height:16px;background:var(--surface-border)"></span>
              <label class="toggle-label">
                <input id="showExternals" type="checkbox" checked>
                <span>Externals</span>
              </label>
              <label class="toggle-label">
                <input id="showLabels" type="checkbox">
                <span>Labels</span>
              </label>
            </div>
          </div>
          <canvas id="graph" aria-label="Architecture topology canvas"></canvas>
        </div>

        <!-- View 2: File Matrix -->
        <div class="view-container" id="view-matrix">
          <div style="max-width:1200px;margin:0 auto;display:flex;flex-direction:column;gap:16px">
            <div class="section-header">
              <h2 style="font-size:18px;font-weight:600">Full Codebase Matrix</h2>
              <span class="badge-counter" id="matrixCount">0 files</span>
            </div>
            <div class="file-table-wrapper" style="max-height:calc(100vh - 180px)">
              <table class="file-table" id="fullMatrixTable">
                <thead>
                  <tr>
                    <th>File Path</th>
                    <th>Language</th>
                    <th style="text-align:right">Code LOC</th>
                    <th style="text-align:right">Blank</th>
                    <th style="text-align:right">Comments</th>
                    <th style="text-align:right">Size</th>
                    <th style="text-align:right">Imports</th>
                    <th style="text-align:right">Symbols</th>
                  </tr>
                </thead>
                <tbody id="matrixTableBody"></tbody>
              </table>
            </div>
          </div>
        </div>

        <!-- View 3: Architecture Insights -->
        <div class="view-container" id="view-insights">
          <div style="max-width:960px;margin:0 auto;display:flex;flex-direction:column;gap:24px">
            <div>
              <h2 style="font-size:20px;font-weight:700;letter-spacing:-0.02em;margin-bottom:6px">Architecture Diagnostics</h2>
              <p style="color:var(--text-muted);font-size:13px">Structural cohesion, dependency centralization, and module coupling analysis.</p>
            </div>
            <div class="stats-grid" id="insightsMetricsGrid" style="grid-template-columns:repeat(auto-fit,minmax(150px,1fr))"></div>
            <div class="section">
              <div class="section-header">
                <span class="section-title">Critical Architectural Hubs (High Centrality)</span>
              </div>
              <div id="hubsContainer" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px"></div>
            </div>
            <div class="section">
              <div class="section-header">
                <span class="section-title">Circular Dependencies</span>
                <span class="badge-counter" id="cyclesCount">0</span>
              </div>
              <div id="cyclesContainer" style="display:flex;flex-direction:column;gap:8px"></div>
            </div>
            <div class="section">
              <div class="section-header">
                <span class="section-title">External Dependency Surface</span>
              </div>
              <div id="externalDepsContainer" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px"></div>
            </div>
          </div>
        </div>
      </section>

      <!-- Right Panel: Inspector -->
      <aside class="panel inspector">
        <div id="inspectorContent" class="inspector-card">
          <h2 class="inspector-title">Architecture snapshot</h2>
          <p class="inspector-desc">
            <b>${pluralize(report.summary.scannedFiles, "source file")}</b> analyzed across <b>${pluralize(report.summary.totalFiles, "total file")}</b> in the repository.
          </p>
          <div class="kv-grid">
            <dt>Code Lines</dt><dd>${escapeHtml(report.humanSummary.lines)}</dd>
            <dt>Physical Lines</dt><dd>${escapeHtml(report.humanSummary.physicalLines)}</dd>
            <dt>Local Edges</dt><dd>${escapeHtml(report.humanSummary.edges)}</dd>
            <dt>External Deps</dt><dd>${escapeHtml(report.summary.externalDependencies)}</dd>
            <dt>Languages</dt><dd>${escapeHtml(report.summary.languages)}</dd>
            <dt>Frameworks</dt><dd>${escapeHtml(report.summary.frameworks)}</dd>
          </div>
          <p class="inspector-desc" style="font-size:12px;color:var(--text-subtle)">
            Select any file or dependency node in the topology graph to inspect imported modules, exported public symbols, and fan-in / fan-out relationships.
          </p>
        </div>
      </aside>
    </main>
  </div>

  <!-- Toast notification banner -->
  <div class="toast" id="toast">Copied to clipboard</div>

  <!-- Embedded Report Data Payload -->
  <script id="report" type="application/json">${payload}</script>
  <script>
    let report = JSON.parse(document.getElementById("report").textContent);
    const sampleProjects = ${samplesPayload};
    const languageColors = ${languagePayload};
    const markdownPayload = ${markdownPayload};

    const canvas = document.getElementById("graph");
    const ctx = canvas.getContext("2d");
    const statusEl = document.getElementById("status");
    const inspector = document.getElementById("inspectorContent");
    const searchInput = document.getElementById("search");
    const matchCounter = document.getElementById("matchCounter");
    const showExternals = document.getElementById("showExternals");
    const showLabels = document.getElementById("showLabels");
    const languageFilters = document.getElementById("languageFilters");
    const themeToggle = document.getElementById("themeToggle");
    const rescanBtn = document.getElementById("rescanBtn");
    const projectSelector = document.getElementById("projectSelector");
    const exportSelector = document.getElementById("exportSelector");
    const toast = document.getElementById("toast");
    const zoomSlider = document.getElementById("zoomSlider");

    let nodes = report.graph.nodes || [];
    let edges = report.graph.edges || [];
    let layout = computeLayout(nodes, edges);

    const state = {
      scale: 1,
      tx: 0,
      ty: 0,
      dragging: false,
      dragStart: null,
      hover: null,
      selected: null,
      query: "",
      languages: new Set(report.stack.languages.map((item) => item.name)),
      dpr: Math.max(1, window.devicePixelRatio || 1),
      theme: localStorage.getItem("stacksketch_theme") || "dark"
    };

    function showToast(msg) {
      toast.textContent = msg;
      toast.classList.add("show");
      setTimeout(() => toast.classList.remove("show"), 2500);
    }

    function applyTheme(theme) {
      state.theme = theme;
      document.documentElement.setAttribute("data-theme", theme);
      localStorage.setItem("stacksketch_theme", theme);
      draw();
    }
    applyTheme(state.theme);

    themeToggle.addEventListener("click", () => {
      applyTheme(state.theme === "dark" ? "light" : "dark");
    });

    function escapeHtml(value) {
      return String(value ?? "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
    }

    function escapeAttr(value) {
      return escapeHtml(value).replace(new RegExp("\\\\x60", "g"), "&#096;");
    }

    function escapeXml(value) {
      return escapeHtml(value).replace(/"/g, "&quot;");
    }

    function pluralize(count, singular, plural) {
      const p = plural || (singular + "s");
      return Number(count || 0).toLocaleString() + " " + (count === 1 ? singular : p);
    }

    function stableHashLocal(value) {
      let hash = 2166136261;
      const text = String(value ?? "");
      for (let index = 0; index < text.length; index += 1) {
        hash ^= text.charCodeAt(index);
        hash = Math.imul(hash, 16777619);
      }
      return hash >>> 0;
    }

    function stableHash(value) {
      return stableHashLocal(value);
    }

    function pluralize(count, singular, plural) {
      const text = plural || \`\${singular}s\`;
      return \`\${Number(count).toLocaleString()} \${count === 1 ? singular : text}\`;
    }

    async function copyText(text) {
      if (navigator.clipboard && window.isSecureContext) {
        try {
          await navigator.clipboard.writeText(text);
          return true;
        } catch (error) {}
      }
      const textarea = document.createElement("textarea");
      textarea.value = text;
      textarea.style.position = "fixed";
      textarea.style.left = "-9999px";
      textarea.style.top = "-9999px";
      document.body.appendChild(textarea);
      textarea.focus();
      textarea.select();
      let copied = false;
      try { copied = document.execCommand("copy"); } catch (error) {}
      textarea.remove();
      return copied;
    }

    function resize() {
      const rect = canvas.getBoundingClientRect();
      state.dpr = Math.max(1, window.devicePixelRatio || 1);
      canvas.width = Math.max(1, Math.floor(rect.width * state.dpr));
      canvas.height = Math.max(1, Math.floor(rect.height * state.dpr));
      ctx.setTransform(state.dpr, 0, 0, state.dpr, 0, 0);
      fit();
    }

    function fit() {
      const rect = canvas.getBoundingClientRect();
      const padding = 200;
      state.scale = Math.max(0.06, Math.min(1.5, Math.min(rect.width, rect.height) / ((layout.bounds.radius || 1000) * 2 + padding * 2)));
      state.tx = rect.width / 2;
      state.ty = rect.height / 2;
      draw();
    }

    function worldToScreen(point) {
      return { x: point.x * state.scale + state.tx, y: point.y * state.scale + state.ty };
    }

    function screenToWorld(point) {
      return { x: (point.x - state.tx) / state.scale, y: (point.y - state.ty) / state.scale };
    }

    function nodeVisible(node) {
      if (node.external && !showExternals.checked) return false;
      if (!state.languages.has(node.language) && !node.external) return false;
      if (state.query && !searchable(node).includes(state.query)) return false;
      return true;
    }

    function searchable(node) {
      return [node.id, node.path, node.name, node.language, ...(node.imports || []), ...(node.exports || [])].join(" ").toLowerCase();
    }

    function visibleNodes() {
      return nodes.filter(nodeVisible);
    }

    function visibleEdges() {
      const set = new Set(visibleNodes().map((node) => node.id));
      return edges.filter((edge) => set.has(edge.source) && set.has(edge.target));
    }

    function draw() {
      const rect = canvas.getBoundingClientRect();
      const width = rect.width;
      const height = rect.height;
      ctx.clearRect(0, 0, width, height);

      const isDark = state.theme === "dark";
      drawGrid(width, height, isDark);

      const visible = visibleNodes();
      const edgeList = visibleEdges();
      matchCounter.textContent = \`\${visible.length} matches\`;

      const connected = new Set();
      if (state.selected) {
        edgeList.forEach((edge) => {
          if (edge.source === state.selected || edge.target === state.selected) {
            connected.add(edge.source);
            connected.add(edge.target);
          }
        });
      }

      ctx.save();
      ctx.translate(state.tx, state.ty);
      ctx.scale(state.scale, state.scale);

      // Draw cluster ring for external boundary
      if (layout.externalRadius && showExternals.checked) {
        ctx.beginPath();
        ctx.arc(0, 0, layout.externalRadius, 0, Math.PI * 2);
        ctx.strokeStyle = isDark ? "rgba(255, 255, 255, 0.08)" : "rgba(0, 0, 0, 0.08)";
        ctx.lineWidth = 1 / state.scale;
        ctx.setLineDash([6 / state.scale, 8 / state.scale]);
        ctx.stroke();
        ctx.setLineDash([]);
      }

      // Draw edges
      for (const edge of edgeList) {
        const source = layout.positions.get(edge.source);
        const target = layout.positions.get(edge.target);
        if (!source || !target) continue;

        const isSelectedEdge = state.selected && (edge.source === state.selected || edge.target === state.selected);
        const isDimmed = state.selected && !isSelectedEdge;

        ctx.beginPath();
        ctx.moveTo(source.x, source.y);
        ctx.lineTo(target.x, target.y);

        if (isSelectedEdge) {
          ctx.strokeStyle = isDark ? "#818cf8" : "#4f46e5";
          ctx.lineWidth = 2.5 / state.scale;
          ctx.globalAlpha = 1;
        } else if (isDimmed) {
          ctx.strokeStyle = isDark ? "rgba(255, 255, 255, 0.04)" : "rgba(0, 0, 0, 0.04)";
          ctx.lineWidth = 0.8 / state.scale;
          ctx.globalAlpha = 0.3;
        } else {
          ctx.strokeStyle = edge.kind === "external"
            ? (isDark ? "rgba(20, 184, 166, 0.28)" : "rgba(13, 148, 136, 0.35)")
            : (isDark ? "rgba(148, 163, 184, 0.22)" : "rgba(71, 85, 105, 0.22)");
          ctx.lineWidth = 1 / state.scale;
          ctx.globalAlpha = 0.8;
        }
        ctx.stroke();
      }
      ctx.globalAlpha = 1;

      // Draw nodes
      for (const node of visible) {
        const point = layout.positions.get(node.id);
        if (!point) continue;

        const screen = worldToScreen(point);
        if (screen.x < -80 || screen.x > width + 80 || screen.y < -80 || screen.y > height + 80) continue;

        const isSelected = state.selected === node.id;
        const isConnected = connected.has(node.id);
        const isHovered = state.hover === node.id;
        const isDimmed = state.selected && !isSelected && !isConnected;

        const radius = point.r || 8;
        ctx.save();
        ctx.globalAlpha = isDimmed ? 0.22 : 1;

        if (node.external) {
          const size = (radius + (isHovered ? 2 : 0)) * 1.8;
          roundRect(ctx, point.x - size / 2, point.y - size / 2, size, size, 4 / state.scale);
          ctx.fillStyle = isDark ? "#14b8a6" : "#0d9488";
          ctx.fill();
        } else {
          ctx.beginPath();
          ctx.arc(point.x, point.y, radius + (isHovered ? 2 : 0), 0, Math.PI * 2);
          ctx.fillStyle = languageColors[node.language] || languageColors.Unknown || "#64748b";
          ctx.fill();
        }

        // Border ring
        ctx.lineWidth = (isSelected ? 3.5 : isConnected ? 2.5 : isHovered ? 2 : 1) / state.scale;
        ctx.strokeStyle = isSelected
          ? (isDark ? "#ffffff" : "#0f172a")
          : isConnected
            ? (isDark ? "#818cf8" : "#4f46e5")
            : isHovered
              ? "#f59e0b"
              : (isDark ? "rgba(255, 255, 255, 0.35)" : "rgba(0, 0, 0, 0.2)");
        ctx.stroke();
        ctx.restore();

        // Node labels
        if (showLabels.checked || isSelected || isHovered || isConnected) {
          const label = shortLabel(node.name || node.path);
          ctx.font = \`\${Math.max(10, 11 / state.scale)}px sans-serif\`;
          const textMetrics = ctx.measureText(label);
          const x = point.x + radius + 6 / state.scale;
          const y = point.y + 3 / state.scale;

          ctx.save();
          ctx.fillStyle = isDark ? "rgba(15, 23, 42, 0.85)" : "rgba(255, 255, 255, 0.9)";
          roundRect(ctx, x - 3 / state.scale, y - 11 / state.scale, textMetrics.width + 6 / state.scale, 14 / state.scale, 3 / state.scale);
          ctx.fill();
          ctx.fillStyle = isDark ? "#f1f5f9" : "#0f172a";
          ctx.fillText(label, x, y);
          ctx.restore();
        }
      }

      ctx.restore();
      statusEl.textContent = \`\${visible.length.toLocaleString()} nodes · \${edgeList.length.toLocaleString()} edges · \${Math.round(state.scale * 100)}% zoom\`;
      zoomSlider.value = state.scale;
    }

    function drawGrid(width, height, isDark) {
      ctx.save();
      ctx.strokeStyle = isDark ? "rgba(255, 255, 255, 0.03)" : "rgba(0, 0, 0, 0.04)";
      ctx.lineWidth = 1;
      const step = 32 * state.scale;
      const offsetX = state.tx % step;
      for (let x = offsetX; x < width; x += step) {
        ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, height); ctx.stroke();
      }
      const offsetY = state.ty % step;
      for (let y = offsetY; y < height; y += step) {
        ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(width, y); ctx.stroke();
      }
      ctx.restore();
    }

    function roundRect(context, x, y, width, height, radius) {
      context.beginPath();
      context.moveTo(x + radius, y);
      context.arcTo(x + width, y, x + width, y + height, radius);
      context.arcTo(x + width, y + height, x, y + height, radius);
      context.arcTo(x, y + height, x, y, radius);
      context.arcTo(x, y, x + width, y, radius);
      context.closePath();
    }

    function shortLabel(value) {
      const text = String(value || "");
      return text.length > 26 ? text.slice(0, 23) + "..." : text;
    }

    function pickNode(event) {
      const rect = canvas.getBoundingClientRect();
      const screen = { x: event.clientX - rect.left, y: event.clientY - rect.top };
      const world = screenToWorld(screen);
      const visible = visibleNodes();
      let best = null;
      let bestDistance = Infinity;

      for (const node of visible) {
        const point = layout.positions.get(node.id);
        if (!point) continue;
        const dx = world.x - point.x;
        const dy = world.y - point.y;
        const distance = Math.sqrt(dx * dx + dy * dy);
        const threshold = (point.r || 8) + 8 / state.scale;
        if (distance < threshold && distance < bestDistance) {
          best = node;
          bestDistance = distance;
        }
      }
      return best;
    }

    function selectNode(node) {
      state.selected = node ? node.id : null;
      renderInspector(node);
      draw();
    }

    function renderInspector(node) {
      if (!node) {
        inspector.innerHTML = \`
          <h2 class="inspector-title">Architecture snapshot</h2>
          <p class="inspector-desc">
            <b>\${escapeHtml(pluralize(report.summary.scannedFiles, "source file"))}</b> scanned from <b>\${escapeHtml(pluralize(report.summary.totalFiles, "total file"))}</b>.
          </p>
          <div class="kv-grid">
            <dt>Code Lines</dt><dd>\${escapeHtml(report.humanSummary.lines)}</dd>
            <dt>Physical Lines</dt><dd>\${escapeHtml(report.humanSummary.physicalLines)}</dd>
            <dt>Local Edges</dt><dd>\${escapeHtml(report.humanSummary.edges)}</dd>
            <dt>External Deps</dt><dd>\${escapeHtml(report.summary.externalDependencies)}</dd>
            <dt>Languages</dt><dd>\${escapeHtml(report.summary.languages)}</dd>
            <dt>Frameworks</dt><dd>\${escapeHtml(report.summary.frameworks)}</dd>
          </div>
          <p class="inspector-desc" style="font-size:12px;color:var(--text-subtle);margin-top:12px">
            Click any node to inspect imports, symbols, LOC, blank lines, comments, and dependency relationships.
          </p>
        \`;
        return;
      }

      // Calculate connected edges
      const inbound = edges.filter((e) => e.target === node.id).map((e) => e.source);
      const outbound = edges.filter((e) => e.source === node.id).map((e) => e.target);

      inspector.innerHTML = \`
        <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:8px">
          <div>
            <span class="chip" style="margin-bottom:6px"><b>\${escapeHtml(node.external ? "External Library" : node.language)}</b></span>
            <h2 class="inspector-title">\${escapeHtml(node.name || node.path)}</h2>
          </div>
          <button class="ghost sm" id="clearInspect" title="Deselect">✕</button>
        </div>
        <p class="inspector-desc" style="font-family:var(--font-mono);font-size:11px">\${escapeHtml(node.path)}</p>

        <div class="kv-grid">
          <dt>Code LOC</dt><dd>\${Number(node.loc || node.codeLines || 0).toLocaleString()}</dd>
          <dt>Blank Lines</dt><dd>\${Number(node.blankLines || 0).toLocaleString()}</dd>
          <dt>Comment Lines</dt><dd>\${Number(node.commentLines || 0).toLocaleString()}</dd>
          <dt>Bytes</dt><dd>\${Number(node.bytes || 0).toLocaleString()}</dd>
          <dt>Inbound Dependents</dt><dd>\${inbound.length}</dd>
          <dt>Outbound Imports</dt><dd>\${outbound.length}</dd>
        </div>

        <div style="display:flex;gap:6px">
          <button class="sm primary" id="copyPathBtn" style="flex:1">Copy Path</button>
          <button class="sm" id="focusNodeBtn" style="flex:1">Focus Center</button>
        </div>

        \${outbound.length ? \`
          <div class="section">
            <span class="section-title">Direct Imports (\${outbound.length})</span>
            <div class="tag-cloud">
              \${outbound.slice(0, 20).map((dep) => \`<span class="tag">\${escapeHtml(dep)}</span>\`).join("")}
            </div>
          </div>
        \` : ""}

        \${inbound.length ? \`
          <div class="section">
            <span class="section-title">Imported By (\${inbound.length})</span>
            <div class="tag-cloud">
              \${inbound.slice(0, 20).map((dep) => \`<span class="tag highlight">\${escapeHtml(dep)}</span>\`).join("")}
            </div>
          </div>
        \` : ""}

        \${(node.exports && node.exports.length) ? \`
          <div class="section">
            <span class="section-title">Exported Symbols (\${node.exports.length})</span>
            <div class="tag-cloud">
              \${node.exports.slice(0, 20).map((sym) => \`<span class="tag">\${escapeHtml(sym)}</span>\`).join("")}
            </div>
          </div>
        \` : ""}
      \`;

      document.getElementById("clearInspect")?.addEventListener("click", () => selectNode(null));
      document.getElementById("copyPathBtn")?.addEventListener("click", async () => {
        await copyText(node.path);
        showToast("Copied path to clipboard!");
      });
      document.getElementById("focusNodeBtn")?.addEventListener("click", () => {
        const point = layout.positions.get(node.id);
        if (point) {
          const rect = canvas.getBoundingClientRect();
          state.scale = Math.max(state.scale, 1.2);
          state.tx = rect.width / 2 - point.x * state.scale;
          state.ty = rect.height / 2 - point.y * state.scale;
          draw();
        }
      });
    }

    function computeLayout(nodes, edges) {
      const positions = new Map();
      const localNodes = nodes.filter((node) => !node.external);
      const externalNodes = nodes.filter((node) => node.external);
      const degree = new Map();
      edges.forEach((edge) => {
        degree.set(edge.source, (degree.get(edge.source) || 0) + 1);
        degree.set(edge.target, (degree.get(edge.target) || 0) + 1);
      });

      const groups = new Map();
      localNodes.forEach((node) => {
        const parts = String(node.path || node.id).split("/");
        const key = parts.length > 2 ? parts.slice(0, 2).join("/") : parts[0] || "root";
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key).push(node);
      });

      const sortedGroups = [...groups.entries()].sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]));
      const groupCount = Math.max(1, sortedGroups.length);
      const localSize = Math.max(1, localNodes.length);
      const baseGraphSize = Math.max(2600, Math.sqrt(localSize) * 135, externalNodes.length * 34);
      const maxRadius = baseGraphSize * 0.38;
      const externalRadius = baseGraphSize * 0.47;

      sortedGroups.forEach(([groupName, group], groupIndex) => {
        const groupAngle = (Math.PI * 2 * groupIndex) / groupCount - Math.PI / 2;
        const groupSize = Math.max(1, group.length);
        const columns = Math.max(5, Math.ceil(Math.sqrt(groupSize)));
        group.sort((a, b) => (degree.get(b.id) || 0) - (degree.get(a.id) || 0) || (b.score || 0) - (a.score || 0));
        group.forEach((node, index) => {
          const row = Math.floor(index / columns);
          const col = index % columns;
          const wedge = Math.PI * 0.95 / Math.max(1, columns);
          const angle = groupAngle - Math.PI * 0.475 + col * wedge + wedge / 2;
          const radial = 100 + row * 64 + ((stableHashLocal(node.id) % 20) - 10);
          const radius = Math.max(10, Math.min(24, 8 + Math.log10((node.score || 1) + 10) * 3.2));
          positions.set(node.id, {
            x: Math.cos(angle) * radial + Math.cos(groupAngle) * 76,
            y: Math.sin(angle) * radial + Math.sin(groupAngle) * 76,
            vx: 0,
            vy: 0,
            r: radius
          });
        });
      });

      const nodeArray = [...positions.entries()].map(([id, point]) => ({ id, ...point }));
      const edgeList = edges.filter((edge) => positions.has(edge.source) && positions.has(edge.target));
      const iterations = Math.min(280, Math.max(130, nodeArray.length * 0.65));
      const repulsion = 22000;
      const attraction = 0.01;
      const desiredDistance = 155;
      const centerForce = 0.006;

      for (let iteration = 0; iteration < iterations; iteration += 1) {
        for (let i = 0; i < nodeArray.length; i += 1) {
          const a = nodeArray[i];
          for (let j = i + 1; j < nodeArray.length; j += 1) {
            const b = nodeArray[j];
            let dx = a.x - b.x;
            let dy = a.y - b.y;
            let distance = Math.sqrt(dx * dx + dy * dy) || 1;
            const minDistance = a.r + b.r + 24;
            if (distance < minDistance) {
              const force = (minDistance - distance) * 0.22;
              dx = (dx / distance) * force;
              dy = (dy / distance) * force;
              a.vx += dx; a.vy += dy;
              b.vx -= dx; b.vy -= dy;
            } else {
              const force = repulsion / (distance * distance);
              dx = (dx / distance) * force;
              dy = (dy / distance) * force;
              a.vx += dx; a.vy += dy;
              b.vx -= dx; b.vy -= dy;
            }
          }
        }

        edgeList.forEach((edge) => {
          const a = positions.get(edge.source);
          const b = positions.get(edge.target);
          if (!a || !b) return;
          let dx = b.x - a.x;
          let dy = b.y - a.y;
          const distance = Math.sqrt(dx * dx + dy * dy) || 1;
          const force = (distance - desiredDistance) * attraction;
          dx = (dx / distance) * force;
          dy = (dy / distance) * force;
          a.vx += dx; a.vy += dy;
          b.vx -= dx; b.vy -= dy;
        });

        nodeArray.forEach((node) => {
          const distance = Math.sqrt(node.x * node.x + node.y * node.y) || 1;
          node.vx -= (node.x / distance) * centerForce * distance;
          node.vy -= (node.y / distance) * centerForce * distance;
          node.vx *= 0.82;
          node.vy *= 0.82;
          node.x += node.vx;
          node.y += node.vy;
          const nodeDistance = Math.sqrt(node.x * node.x + node.y * node.y);
          const limit = maxRadius - node.r;
          if (nodeDistance > limit) {
            node.x = (node.x / nodeDistance) * limit;
            node.y = (node.y / nodeDistance) * limit;
          }
        });
      }

      nodeArray.forEach((node) => positions.set(node.id, { x: node.x, y: node.y, r: node.r }));

      externalNodes.sort((a, b) => (b.score || 0) - (a.score || 0) || a.id.localeCompare(b.id)).forEach((node, index) => {
        const angle = (Math.PI * 2 * index) / Math.max(1, externalNodes.length) - Math.PI / 2;
        const radius = externalRadius + (stableHashLocal(node.id) % 90);
        positions.set(node.id, { x: Math.cos(angle) * radius, y: Math.sin(angle) * radius, vx: 0, vy: 0, r: 12 });
      });

      const important = new Set([...nodes].sort((a, b) => (b.score || 0) - (a.score || 0)).slice(0, 120).map((node) => node.id));
      return { positions, important, externalRadius, bounds: { radius: externalRadius + 280 } };
    }

    function downloadSvg() {
      const visible = visibleNodes();
      const edgeList = visibleEdges().slice(0, 5000);
      const radius = (layout.externalRadius || layout.bounds.radius) + 260;
      const size = radius * 2;
      const padding = 120;
      const important = new Set([...nodes].sort((a, b) => (b.score || 0) - (a.score || 0)).slice(0, 180).map((node) => node.id));
      let svg = \`<svg xmlns="http://www.w3.org/2000/svg" width="\${size + padding * 2}" height="\${size + padding * 2}" viewBox="\${-radius - padding} \${-radius - padding} \${size + padding * 2} \${size + padding * 2}">
        <rect width="100%" height="100%" fill="\${state.theme === "dark" ? "#090d16" : "#f8fafc"}"/>
        <title>\${escapeXml(report.title)} architecture map</title>
        <desc>\${escapeXml(visible.length)} nodes and \${escapeXml(edgeList.length)} edges</desc>\`;

      for (const edge of edgeList) {
        const source = layout.positions.get(edge.source);
        const target = layout.positions.get(edge.target);
        if (!source || !target) continue;
        svg += \`<path d="M \${source.x} \${source.y} L \${target.x} \${target.y}" stroke="\${edge.kind === "external" ? "#14b8a6" : "#64748b"}" stroke-opacity="0.25" stroke-width="1" fill="none"/>\`;
      }

      for (const node of visible) {
        const point = layout.positions.get(node.id);
        if (!point) continue;
        const color = languageColors[node.language] || languageColors.Unknown || "#94a3b8";
        svg += \`<circle cx="\${point.x}" cy="\${point.y}" r="\${point.r || 7}" fill="\${color}" stroke="rgba(255,255,255,0.65)" stroke-width="1"/>\`;
        if (important.has(node.id) || state.selected === node.id) {
          svg += \`<text x="\${point.x + (point.r || 7) + 8}" y="\${point.y + 4}" fill="\${state.theme === "dark" ? "#f1f5f9" : "#0f172a"}" font-size="12" font-family="sans-serif">\${escapeXml(shortLabel(node.name || node.path))}</text>\`;
        }
      }

      svg += \`</svg>\`;
      const blob = new Blob([svg], { type: "image/svg+xml;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = \`\${report.title.replace(/[^a-z0-9_-]/gi, "_")}-architecture.svg\`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
      showToast("SVG exported successfully!");
    }

    function downloadPng() {
      const link = document.createElement("a");
      link.download = \`\${report.title.replace(/[^a-z0-9_-]/gi, "_")}-architecture.png\`;
      link.href = canvas.toDataURL("image/png");
      document.body.appendChild(link);
      link.click();
      link.remove();
      showToast("PNG image exported!");
    }

    function downloadJson() {
      const blob = new Blob([JSON.stringify(report, null, 2)], { type: "application/json;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = \`\${report.title.replace(/[^a-z0-9_-]/gi, "_")}-stacksketch.json\`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
      showToast("JSON dataset exported!");
    }

    // Canvas interactions
    canvas.addEventListener("wheel", (event) => {
      event.preventDefault();
      const rect = canvas.getBoundingClientRect();
      const mouse = { x: event.clientX - rect.left, y: event.clientY - rect.top };
      const before = screenToWorld(mouse);
      const factor = event.deltaY < 0 ? 1.12 : 0.88;
      state.scale = Math.max(0.05, Math.min(4, state.scale * factor));
      state.tx = mouse.x - before.x * state.scale;
      state.ty = mouse.y - before.y * state.scale;
      draw();
    }, { passive: false });

    canvas.addEventListener("mousedown", (event) => {
      const node = pickNode(event);
      if (node) {
        selectNode(node);
        return;
      }
      state.dragging = true;
      state.dragStart = { x: event.clientX, y: event.clientY, tx: state.tx, ty: state.ty };
      canvas.classList.add("dragging");
    });

    window.addEventListener("mousemove", (event) => {
      if (state.dragging && state.dragStart) {
        state.tx = state.dragStart.tx + event.clientX - state.dragStart.x;
        state.ty = state.dragStart.ty + event.clientY - state.dragStart.y;
        draw();
      } else {
        const node = pickNode(event);
        if (state.hover !== (node && node.id)) {
          state.hover = node ? node.id : null;
          canvas.style.cursor = node ? "pointer" : "grab";
          draw();
        }
      }
    });

    window.addEventListener("mouseup", () => {
      state.dragging = false;
      state.dragStart = null;
      canvas.classList.remove("dragging");
    });

    searchInput.addEventListener("input", () => {
      state.query = searchInput.value.trim().toLowerCase();
      draw();
      updateMatrixView();
    });

    showExternals.addEventListener("change", draw);
    showLabels.addEventListener("change", draw);

    languageFilters.addEventListener("change", () => {
      state.languages = new Set([...languageFilters.querySelectorAll("input:checked")].map((i) => i.value));
      draw();
      updateMatrixView();
    });

    document.getElementById("toggleAllLangs")?.addEventListener("click", () => {
      const inputs = languageFilters.querySelectorAll("input");
      const allChecked = [...inputs].every((i) => i.checked);
      inputs.forEach((i) => { i.checked = !allChecked; });
      state.languages = new Set([...languageFilters.querySelectorAll("input:checked")].map((i) => i.value));
      draw();
      updateMatrixView();
    });

    document.getElementById("fit").addEventListener("click", fit);
    document.getElementById("zoomIn").addEventListener("click", () => {
      state.scale = Math.min(4, state.scale * 1.25);
      draw();
    });
    document.getElementById("zoomOut").addEventListener("click", () => {
      state.scale = Math.max(0.05, state.scale * 0.8);
      draw();
    });
    zoomSlider.addEventListener("input", () => {
      state.scale = Math.max(0.05, Math.min(4, parseFloat(zoomSlider.value) || 1));
      draw();
    });
    document.getElementById("reset").addEventListener("click", () => {
      searchInput.value = "";
      state.query = "";
      state.selected = null;
      state.hover = null;
      showExternals.checked = true;
      showLabels.checked = false;
      languageFilters.querySelectorAll("input").forEach((input) => { input.checked = true; });
      state.languages = new Set(report.stack.languages.map((item) => item.name));
      fit();
      renderInspector(null);
    });

    // View Switching
    document.querySelectorAll(".nav-tab").forEach((tab) => {
      tab.addEventListener("click", () => {
        document.querySelectorAll(".nav-tab").forEach((t) => t.classList.remove("active"));
        tab.classList.add("active");
        const view = tab.getAttribute("data-view");
        document.querySelectorAll(".view-container").forEach((vc) => vc.classList.remove("active"));
        const targetView = document.getElementById(\`view-\${view}\`);
        if (targetView) targetView.classList.add("active");
        if (view === "graph") {
          resize();
        } else if (view === "matrix") {
          updateMatrixView();
        } else if (view === "insights") {
          updateInsightsView();
        }
      });
    });

    // Populate Matrix view
    function updateMatrixView() {
      const tbody = document.getElementById("matrixTableBody");
      const counter = document.getElementById("matrixCount");
      const visible = visibleNodes().filter((n) => !n.external);
      counter.textContent = \`\${visible.length} files\`;

      tbody.innerHTML = visible.slice(0, 150).map((file) => \`
        <tr data-node-id="\${escapeAttr(file.id)}">
          <td><code title="\${escapeAttr(file.path)}">\${escapeHtml(file.path)}</code></td>
          <td><span class="chip" style="padding:2px 6px">\${escapeHtml(file.language)}</span></td>
          <td class="num">\${Number(file.loc || file.codeLines || 0).toLocaleString()}</td>
          <td class="num">\${Number(file.blankLines || 0).toLocaleString()}</td>
          <td class="num">\${Number(file.commentLines || 0).toLocaleString()}</td>
          <td class="num">\${Number(file.bytes || 0).toLocaleString()} B</td>
          <td class="num">\${(file.imports || []).length}</td>
          <td class="num">\${(file.exports || []).length}</td>
        </tr>
      \`).join("");

      tbody.querySelectorAll("tr").forEach((row) => {
        row.addEventListener("click", () => {
          const id = row.getAttribute("data-node-id");
          const target = nodes.find((n) => n.id === id);
          if (target) {
            document.querySelector('[data-view="graph"]').click();
            selectNode(target);
            const point = layout.positions.get(target.id);
            if (point) {
              const rect = canvas.getBoundingClientRect();
              state.scale = 1.3;
              state.tx = rect.width / 2 - point.x * state.scale;
              state.ty = rect.height / 2 - point.y * state.scale;
              draw();
            }
          }
        });
      });
    }

    // Populate Insights view
    function updateInsightsView() {
      const grid = document.getElementById("insightsMetricsGrid");
      const hubs = document.getElementById("hubsContainer");
      const externals = document.getElementById("externalDepsContainer");
      const cyclesContainer = document.getElementById("cyclesContainer");
      const cyclesCounter = document.getElementById("cyclesCount");

      const inDegree = new Map();
      const outDegree = new Map();
      edges.forEach((e) => {
        outDegree.set(e.source, (outDegree.get(e.source) || 0) + 1);
        inDegree.set(e.target, (inDegree.get(e.target) || 0) + 1);
      });

      const localNodes = nodes.filter((n) => !n.external);
      const topHubs = [...localNodes]
        .sort((a, b) => ((inDegree.get(b.id) || 0) + (outDegree.get(b.id) || 0)) - ((inDegree.get(a.id) || 0) + (outDegree.get(a.id) || 0)))
        .slice(0, 6);

      const externalNodes = nodes.filter((n) => n.external);
      const cycles = (report.insights && report.insights.cycles) || [];
      if (cyclesCounter) cyclesCounter.textContent = cycles.length;

      grid.innerHTML = \`
        <div class="metric-card"><strong>\${localNodes.length}</strong><span>Local Modules</span></div>
        <div class="metric-card"><strong>\${edges.length}</strong><span>Dependency Edges</span></div>
        <div class="metric-card"><strong>\${externalNodes.length}</strong><span>External Libraries</span></div>
        <div class="metric-card"><strong>\${cycles.length}</strong><span>Circular Modules</span></div>
        <div class="metric-card"><strong>\${report.stack.frameworks.length || "0"}</strong><span>Frameworks</span></div>
      \`;

      hubs.innerHTML = topHubs.map((hub) => \`
        <div class="metric-card" style="cursor:pointer" data-hub-id="\${escapeAttr(hub.id)}">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:4px">
            <span class="chip" style="font-size:10px">\${escapeHtml(hub.language)}</span>
            <span class="badge-counter">\${(inDegree.get(hub.id) || 0) + (outDegree.get(hub.id) || 0)} links</span>
          </div>
          <strong style="font-size:13px;word-break:break-all">\${escapeHtml(hub.path)}</strong>
          <span style="margin-top:4px">Imported by \${inDegree.get(hub.id) || 0} files · Imports \${outDegree.get(hub.id) || 0} files</span>
        </div>
      \`).join("");

      hubs.querySelectorAll("[data-hub-id]").forEach((el) => {
        el.addEventListener("click", () => {
          const id = el.getAttribute("data-hub-id");
          const target = nodes.find((n) => n.id === id);
          if (target) {
            document.querySelector('[data-view="graph"]').click();
            selectNode(target);
          }
        });
      });

      if (cyclesContainer) {
        cyclesContainer.innerHTML = cycles.length
          ? cycles.map((cycle) => \`
              <div class="metric-card" style="padding:8px 10px">
                <div style="display:flex;align-items:center;gap:6px;flex-wrap:wrap">
                  \${cycle.nodes.map((id, index) => \`
                    <span class="tag" style="cursor:pointer" data-cycle-node="\${escapeAttr(id)}">\${escapeHtml(id)}</span>
                    \${index < cycle.nodes.length - 1 ? '<span style="color:var(--text-subtle)">\\u2192</span>' : ""}
                  \`).join("")}
                </div>
              </div>
            \`).join("")
          : '<p style="color:var(--text-muted);font-size:13px">No circular dependencies detected \\u2014 healthy module topology.</p>';

        cyclesContainer.querySelectorAll("[data-cycle-node]").forEach((el) => {
          el.addEventListener("click", () => {
            const id = el.getAttribute("data-cycle-node");
            const target = nodes.find((n) => n.id === id);
            if (target) {
              document.querySelector('[data-view="graph"]').click();
              selectNode(target);
            }
          });
        });
      }

      externals.innerHTML = externalNodes.slice(0, 15).map((ext) => \`
        <div class="metric-card">
          <strong style="font-size:13px">\${escapeHtml(ext.name || ext.id)}</strong>
          <span>\${inDegree.get(ext.id) || ext.count || 1} repository references</span>
        </div>
      \`).join("") || '<p style="color:var(--text-muted);font-size:13px">No external dependencies identified.</p>';
    }

    // Export handler
    exportSelector.addEventListener("change", async (e) => {
      const val = e.target.value;
      e.target.value = "";
      if (val === "svg") {
        downloadSvg();
      } else if (val === "png") {
        downloadPng();
      } else if (val === "markdown") {
        await copyText(markdownPayload);
        showToast("Markdown architecture report copied!");
      } else if (val === "json") {
        downloadJson();
      }
    });

    function refreshLanguageFiltersUI() {
      if (!languageFilters || !report.stack || !report.stack.languages) return;
      languageFilters.innerHTML = report.stack.languages.map((l) => \`
        <label class="check-item">
          <div class="check-item-left">
            <input type="checkbox" value="\${escapeAttr(l.name)}" checked>
            <span class="legend-dot" style="background:\${escapeAttr(languageColors[l.name] || '#94a3b8')}"></span>
            <span>\${escapeHtml(l.name)}</span>
          </div>
          <span class="badge-counter">\${l.files}</span>
        </label>
      \`).join("");
    }

    // Interactive directory tree
    let treeExpanded = false;

    function countTreeFiles(node) {
      if (!node) return 0;
      if (node.type === "file") return 1;
      return (node.children || []).reduce((total, child) => total + countTreeFiles(child), 0);
    }

    function treeNodeHtml(node, depth) {
      if (node.type === "file") {
        const dot = node.language && languageColors[node.language]
          ? \`style="background:\${escapeAttr(languageColors[node.language])}"\`
          : "";
        return \`<div class="tree-file" data-tree-file="\${escapeAttr(node.path || node.name)}" title="\${escapeAttr(node.path || node.name)}">
          <span class="tree-icon" \${dot}></span>
          <span class="tree-name">\${escapeHtml(node.name)}</span>
        </div>\`;
      }
      const children = node.children || [];
      const fileCount = countTreeFiles(node);
      return \`<details class="tree-folder"\${depth < 2 ? " open" : ""}>
        <summary class="tree-folder-head" title="\${escapeAttr(node.name)}">
          <span class="tree-twisty"></span>
          <span class="tree-icon folder"></span>
          <span class="tree-name">\${escapeHtml(node.name)}</span>
          <span class="tree-count">\${fileCount}</span>
        </summary>
        <div class="tree-children">
          \${children.map((child) => treeNodeHtml(child, depth + 1)).join("")}
        </div>
      </details>\`;
    }

    function renderDirectoryTree() {
      const container = document.getElementById("directoryTree");
      if (!container) return;
      const root = report.directoryTree;
      if (!root || !(root.children || []).length) {
        container.innerHTML = '<span class="tree-name" style="padding:4px">No files scanned.</span>';
        return;
      }
      container.innerHTML = root.children
        .map((child) => treeNodeHtml(child, 0))
        .join("");

      container.querySelectorAll("[data-tree-file]").forEach((el) => {
        el.addEventListener("click", () => {
          const target = nodes.find((n) => n.path === el.getAttribute("data-tree-file"));
          if (target) {
            document.querySelector('[data-view="graph"]').click();
            selectNode(target);
          }
        });
      });

      const note = document.getElementById("treeNote");
      if (note) {
        note.style.display = report.summary.maxFilesReached ? "block" : "none";
        note.textContent = "Scan hit the max-files limit \\u2014 this tree is a partial view. Raise --max-files to include the rest.";
      }
      syncExpandButton();
    }

    function syncExpandButton() {
      const btn = document.getElementById("expandAllTree");
      if (btn) btn.textContent = treeExpanded ? "Collapse" : "Expand";
    }

    document.getElementById("expandAllTree")?.addEventListener("click", () => {
      treeExpanded = !treeExpanded;
      document.querySelectorAll("#directoryTree details").forEach((d) => { d.open = treeExpanded; });
      syncExpandButton();
    });

    // Sample switcher
    projectSelector.addEventListener("change", async (e) => {
      const val = e.target.value;
      if (val === "local") {
        location.reload();
        return;
      }
      const sample = sampleProjects[val];
      if (sample) {
        report = sample;
        nodes = report.graph.nodes || [];
        edges = report.graph.edges || [];
        layout = computeLayout(nodes, edges);
        state.languages = new Set(report.stack.languages.map((i) => i.name));
        refreshLanguageFiltersUI();
        fit();
        renderInspector(null);
        showToast(\`Loaded \${sample.title}\`);
      }
    });

    // Re-scan trigger
    rescanBtn.addEventListener("click", async () => {
      rescanBtn.style.opacity = "0.5";
      showToast("Scanning codebase...");
      try {
        const res = await fetch("/api/report?refresh=1");
        if (res.ok) {
          report = await res.json();
          nodes = report.graph.nodes || [];
          edges = report.graph.edges || [];
          layout = computeLayout(nodes, edges);
          state.languages = new Set(report.stack.languages.map((i) => i.name));
          refreshLanguageFiltersUI();
          renderDirectoryTree();
          fit();
          renderInspector(null);
          showToast("Scan complete!");
        } else {
          location.reload();
        }
      } catch (err) {
        location.reload();
      } finally {
        rescanBtn.style.opacity = "1";
      }
    });

    // Hotkeys: Ctrl+K or Cmd+K to focus search
    window.addEventListener("keydown", (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        searchInput.focus();
      }
    });

    // Initialize layout
    window.addEventListener("resize", resize);
    resize();
    renderInspector(null);
    renderDirectoryTree();
  </script>
</body>
</html>`;
}

function renderFrameworks(report) {
  if (!report.stack.frameworks.length) return `<span class="chip">None detected</span>`;
  return report.stack.frameworks.map((framework) => `<span class="chip"><b>${escapeHtml(framework)}</b></span>`).join("");
}

function renderScanScope(report) {
  const unlimited = !report.summary.maxFiles || !Number.isFinite(report.summary.maxFiles);
  return [
    `<span class="chip"><b>${unlimited ? "no limit" : escapeHtml(report.summary.maxFiles)}</b> max files</span>`,
    `<span class="chip">${report.summary.maxFilesReached ? "truncated" : "complete scan"}</span>`,
    `<span class="chip"><b>${escapeHtml(report.summary.externalDependencies)}</b> externals</span>`,
    `<span class="chip"><b>${escapeHtml(report.summary.totalBlankLines.toLocaleString())}</b> blanks</span>`,
    `<span class="chip"><b>${escapeHtml(report.summary.totalCommentLines.toLocaleString())}</b> comments</span>`
  ].join("");
}

function renderLanguageFilters(report) {
  return report.stack.languages.map((language) => `
    <label class="check-item">
      <div class="check-item-left">
        <input type="checkbox" value="${escapeAttr(language.name)}" checked>
        <span class="legend-dot" style="background:${escapeAttr(LANGUAGE_COLORS[language.name] || '#94a3b8')}"></span>
        <span>${escapeHtml(language.name)}</span>
      </div>
      <span class="badge-counter">${language.files}</span>
    </label>
  `).join("");
}

function renderTopFiles(report) {
  return report.topFiles.slice(0, 10).map((file) => `
    <tr>
      <td><code title="${escapeAttr(file.path)}">${escapeHtml(file.path)}</code></td>
      <td class="num">${file.loc}</td>
      <td class="num">${file.imports.length}</td>
    </tr>
  `).join("");
}

function renderExternalDependencies(report) {
  const deps = report.graph.nodes.filter((node) => node.external).slice(0, 18);
  if (!deps.length) return `<div class="chip">No external dependencies detected</div>`;
  return deps.map((dep) => `
    <div class="metric-card" style="padding:6px 8px">
      <strong style="font-size:12px">${escapeHtml(dep.name || dep.id)}</strong>
      <span style="font-size:10px">${Number(dep.count || dep.lines || 0).toLocaleString()} imports</span>
    </div>
  `).join("");
}

module.exports = {
  renderHtml
};
