const {
  LANGUAGE_COLORS,
  normalizeFilePath
} = require("./defaults");
const {
  bytesToSize,
  escapeAttr,
  escapeHtml,
  pluralize,
  stableHash
} = require("./utils");
const { formatMarkdown } = require("./analyzer");

function renderHtml(report) {
  const payload = JSON.stringify(report).replace(/</g, "\\u003c");
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(report.title)} · StackSketch</title>
  <meta name="description" content="A local-first architecture map generated by StackSketch.">
  <style>
    :root {
      color-scheme: dark;
      --bg: #070a12;
      --panel: rgba(15, 23, 42, 0.78);
      --panel-strong: rgba(15, 23, 42, 0.96);
      --text: #e5e7eb;
      --muted: #94a3b8;
      --line: rgba(148, 163, 184, 0.22);
      --accent: #7c3aed;
      --accent-2: #22d3ee;
      --good: #34d399;
      --warn: #fbbf24;
      --danger: #fb7185;
      --shadow: 0 24px 80px rgba(0, 0, 0, 0.35);
      --radius: 22px;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }

    * { box-sizing: border-box; }

    body {
      margin: 0;
      min-height: 100vh;
      background:
        radial-gradient(circle at 12% 8%, rgba(124, 58, 237, 0.32), transparent 28rem),
        radial-gradient(circle at 88% 18%, rgba(34, 211, 238, 0.20), transparent 26rem),
        radial-gradient(circle at 50% 100%, rgba(16, 185, 129, 0.12), transparent 30rem),
        var(--bg);
      color: var(--text);
    }

    button, input {
      font: inherit;
    }

    .app {
      min-height: 100vh;
      display: grid;
      grid-template-columns: minmax(300px, 390px) 1fr;
      gap: 18px;
      padding: 18px;
    }

    .sidebar, .panel {
      border: 1px solid rgba(148, 163, 184, 0.18);
      background: var(--panel);
      backdrop-filter: blur(20px);
      border-radius: var(--radius);
      box-shadow: var(--shadow);
    }

    .sidebar {
      overflow: auto;
      padding: 20px;
    }

    .brand {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 18px;
    }

    .logo {
      width: 42px;
      height: 42px;
      display: grid;
      place-items: center;
      border-radius: 14px;
      background: linear-gradient(135deg, var(--accent), var(--accent-2));
      box-shadow: 0 14px 34px rgba(34, 211, 238, 0.22);
      font-weight: 900;
    }

    h1 {
      margin: 0;
      font-size: 20px;
      line-height: 1.1;
      letter-spacing: -0.03em;
    }

    .subtitle {
      margin: 4px 0 0;
      color: var(--muted);
      font-size: 13px;
    }

    .stats {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 10px;
      margin: 18px 0;
    }

    .stat {
      padding: 14px;
      border: 1px solid rgba(148, 163, 184, 0.16);
      border-radius: 16px;
      background: rgba(2, 6, 23, 0.38);
    }

    .stat strong {
      display: block;
      font-size: 20px;
      letter-spacing: -0.03em;
    }

    .stat span {
      display: block;
      margin-top: 3px;
      color: var(--muted);
      font-size: 12px;
    }

    .search {
      width: 100%;
      border: 1px solid rgba(148, 163, 184, 0.24);
      background: rgba(2, 6, 23, 0.55);
      color: var(--text);
      border-radius: 14px;
      padding: 12px 14px;
      outline: none;
    }

    .search:focus {
      border-color: rgba(34, 211, 238, 0.7);
      box-shadow: 0 0 0 4px rgba(34, 211, 238, 0.12);
    }

    .section {
      margin-top: 20px;
    }

    .section h2 {
      margin: 0 0 10px;
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.14em;
      color: var(--muted);
    }

    .chips {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
    }

    .chip {
      border: 1px solid rgba(148, 163, 184, 0.18);
      border-radius: 999px;
      padding: 7px 10px;
      color: #cbd5e1;
      background: rgba(2, 6, 23, 0.35);
      font-size: 12px;
    }

    .chip b {
      color: white;
    }

    .toolbar {
      display: flex;
      gap: 8px;
      margin-bottom: 12px;
    }

    .toolbar button, .copy-button {
      border: 1px solid rgba(148, 163, 184, 0.22);
      background: rgba(2, 6, 23, 0.48);
      color: var(--text);
      border-radius: 12px;
      padding: 9px 11px;
      cursor: pointer;
    }

    .toolbar button:hover, .copy-button:hover {
      border-color: rgba(34, 211, 238, 0.55);
    }

    .canvas-wrap {
      position: relative;
      overflow: hidden;
      border-radius: var(--radius);
    }

    svg {
      display: block;
      width: 100%;
      height: calc(100vh - 36px);
      min-height: 720px;
      background:
        linear-gradient(rgba(148, 163, 184, 0.045) 1px, transparent 1px),
        linear-gradient(90deg, rgba(148, 163, 184, 0.045) 1px, transparent 1px);
      background-size: 34px 34px;
    }

    .edge {
      stroke: rgba(148, 163, 184, 0.18);
      stroke-width: 1.1;
    }

    .edge.external {
      stroke: rgba(34, 211, 238, 0.16);
      stroke-dasharray: 5 7;
    }

    .node circle {
      stroke: rgba(255, 255, 255, 0.75);
      stroke-width: 1.2;
      filter: drop-shadow(0 10px 18px rgba(0, 0, 0, 0.35));
      cursor: pointer;
      transition: r 0.16s ease, opacity 0.16s ease;
    }

    .node text {
      fill: rgba(226, 232, 240, 0.88);
      font-size: 11px;
      pointer-events: none;
      paint-order: stroke;
      stroke: rgba(7, 10, 18, 0.9);
      stroke-width: 4px;
      stroke-linejoin: round;
    }

    .node.hidden, .edge.hidden {
      opacity: 0.06;
    }

    .node.selected circle {
      stroke: white;
      stroke-width: 3;
      r: 13;
    }

    .details {
      position: absolute;
      right: 18px;
      bottom: 18px;
      width: min(420px, calc(100% - 36px));
      max-height: 52vh;
      overflow: auto;
      padding: 16px;
      border: 1px solid rgba(148, 163, 184, 0.22);
      border-radius: 18px;
      background: var(--panel-strong);
      box-shadow: var(--shadow);
    }

    .details h3 {
      margin: 0 0 8px;
      word-break: break-word;
    }

    .details p {
      margin: 6px 0;
      color: var(--muted);
      font-size: 13px;
    }

    .details code {
      color: #bfdbfe;
      word-break: break-all;
    }

    .tree {
      margin: 0;
      padding: 0;
      list-style: none;
      font-size: 12px;
      color: #cbd5e1;
    }

    .tree ul {
      margin: 0 0 0 14px;
      padding-left: 10px;
      border-left: 1px solid rgba(148, 163, 184, 0.16);
    }

    .tree li {
      margin: 4px 0;
      white-space: nowrap;
    }

    .tree .file {
      color: #93c5fd;
    }

    .legend {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 6px;
    }

    .legend span {
      display: flex;
      align-items: center;
      gap: 7px;
      color: var(--muted);
      font-size: 12px;
    }

    .dot {
      width: 9px;
      height: 9px;
      border-radius: 99px;
      background: var(--dot);
    }

    .footer {
      margin-top: 18px;
      color: var(--muted);
      font-size: 12px;
      line-height: 1.5;
    }

    @media (max-width: 980px) {
      .app {
        grid-template-columns: 1fr;
      }
      .sidebar {
        order: 2;
      }
      svg {
        min-height: 620px;
      }
    }
  </style>
</head>
<body>
  <main class="app">
    <aside class="sidebar">
      <div class="brand">
        <div class="logo">S</div>
        <div>
          <h1>${escapeHtml(report.title)}</h1>
          <p class="subtitle">Generated by StackSketch</p>
        </div>
      </div>

      <div class="stats">
        <div class="stat"><strong>${escapeHtml(report.humanSummary.files)}</strong><span>Files</span></div>
        <div class="stat"><strong>${escapeHtml(report.humanSummary.lines)}</strong><span>Lines</span></div>
        <div class="stat"><strong>${escapeHtml(report.humanSummary.size)}</strong><span>Size</span></div>
        <div class="stat"><strong>${escapeHtml(report.humanSummary.edges)}</strong><span>Edges</span></div>
      </div>

      <input id="search" class="search" type="search" placeholder="Search files, languages, dependencies..." autocomplete="off">

      <div class="section">
        <h2>Frameworks</h2>
        <div class="chips">
          ${report.stack.frameworks.length ? report.stack.frameworks.map((framework) => `<span class="chip">${escapeHtml(framework)}</span>`).join("") : `<span class="chip">Not detected</span>`}
        </div>
      </div>

      <div class="section">
        <h2>Languages</h2>
        <div class="legend">
          ${report.stack.languages.map((language) => `<span><i class="dot" style="--dot:${escapeAttr(LANGUAGE_COLORS[language.name] || "#94a3b8")}"></i><b>${escapeHtml(language.name)}</b> ${language.files}</span>`).join("")}
        </div>
      </div>

      <div class="section">
        <h2>Top Files</h2>
        <div class="chips">
          ${report.topFiles.slice(0, 10).map((file) => `<span class="chip"><b>${escapeHtml(file.loc)}</b> ${escapeHtml(file.path)}</span>`).join("")}
        </div>
      </div>

      <div class="section">
        <h2>Directory</h2>
        <ul class="tree">${renderTree(report.directoryTree)}</ul>
      </div>

      <p class="footer">
        This report is generated locally. No source code is uploaded anywhere.
        Open the HTML file in a browser to explore the architecture map.
      </p>
    </aside>

    <section class="panel">
      <div class="toolbar">
        <button id="reset">Reset view</button>
        <button id="zoomIn">Zoom in</button>
        <button id="zoomOut">Zoom out</button>
        <button id="download">Download SVG</button>
        <button id="copyMarkdown">Copy Markdown</button>
      </div>
      <div class="canvas-wrap">
        <svg id="graph" role="img" aria-label="Architecture graph"></svg>
        <article class="details" id="details">
          <h3>Architecture snapshot</h3>
          <p><b>${pluralize(report.summary.fileCount, "file")}</b> and <b>${pluralize(report.summary.importEdges, "edge")}</b> mapped from local imports.</p>
          <p>Click any node to inspect imports, exports, LOC, and dependencies.</p>
        </article>
      </div>
    </section>
  </main>

  <script id="report" type="application/json">${payload}</script>
  <script>
    const report = JSON.parse(document.getElementById("report").textContent);
    const svg = document.getElementById("graph");
    const details = document.getElementById("details");
    const search = document.getElementById("search");
    const nodes = report.graph.nodes;
    const edges = report.graph.edges;
    let scale = 1;
    let selectedId = null;

    const languageColors = ${JSON.stringify(LANGUAGE_COLORS).replace(/</g, "\\u003c")};
    const layout = layoutNodes(nodes, edges);
    renderGraph();
    bindControls();

    function bindControls() {
      document.getElementById("reset").addEventListener("click", () => {
        scale = 1;
        selectedId = null;
        search.value = "";
        renderGraph();
      });
      document.getElementById("zoomIn").addEventListener("click", () => {
        scale = Math.min(scale * 1.18, 3.2);
        renderGraph();
      });
      document.getElementById("zoomOut").addEventListener("click", () => {
        scale = Math.max(scale / 1.18, 0.35);
        renderGraph();
      });
      document.getElementById("download").addEventListener("click", downloadSvg);
      document.getElementById("copyMarkdown").addEventListener("click", async () => {
        const markdown = ${JSON.stringify(formatMarkdown(report)).replace(/</g, "\\u003c")};
        await navigator.clipboard.writeText(markdown);
        details.innerHTML = "<h3>Markdown copied</h3><p>Use it in a PR, README, or onboarding doc.</p>";
      });
      search.addEventListener("input", renderGraph);
    }

    function renderGraph() {
      const query = search.value.trim().toLowerCase();
      const visibleNodes = new Set(nodes.filter((node) => !query || searchable(node).includes(query)).map((node) => node.id));
      const visibleEdges = edges.filter((edge) => visibleNodes.has(edge.source) && visibleNodes.has(edge.target));
      const width = Math.max(980, svg.clientWidth || 1200);
      const height = Math.max(720, svg.clientHeight || 900);
      const transform = \`translate(\${width / 2}, \${height / 2}) scale(\${scale})\`;
      svg.setAttribute("viewBox", \`0 0 \${width} \${height}\`);
      svg.innerHTML = \`<defs>
        <marker id="arrow" markerWidth="8" markerHeight="8" refX="8" refY="4" orient="auto">
          <path d="M0,0 L8,4 L0,8 Z" fill="rgba(148,163,184,0.35)"></path>
        </marker>
      </defs><g transform="\${transform}">\${renderEdges(visibleEdges)}\${renderNodes(visibleNodes, visibleEdges)}</g>\`;
    }

    function renderEdges(visibleEdges) {
      return visibleEdges.map((edge) => {
        const source = layout.get(edge.source);
        const target = layout.get(edge.target);
        if (!source || !target) return "";
        const dx = target.x - source.x;
        const dy = target.y - source.y;
        const curve = Math.sqrt(dx * dx + dy * dy) * 0.18;
        return \`<path class="edge \${edge.kind === "external" ? "external" : ""}" d="M \${source.x} \${source.y} C \${source.x + curve} \${source.y}, \${target.x - curve} \${target.y}, \${target.x} \${target.y}" marker-end="url(#arrow)"></path>\`;
      }).join("");
    }

    function renderNodes(visibleNodes, visibleEdges) {
      const connected = new Set();
      visibleEdges.forEach((edge) => {
        connected.add(edge.source);
        connected.add(edge.target);
      });
      return nodes.map((node) => {
        const point = layout.get(node.id);
        if (!point) return "";
        const color = languageColors[node.language] || languageColors.Unknown || "#94a3b8";
        const hidden = !visibleNodes.has(node.id);
        const selected = selectedId === node.id ? "selected" : "";
        const radius = Math.max(6, Math.min(18, 5 + Math.log10(node.score + 10) * 3.2));
        return \`<g class="node \${hidden ? "hidden" : ""} \${selected}" transform="translate(\${point.x}, \${point.y})" data-id="\${escapeAttr(node.id)}">
          <circle r="\${radius}" fill="\${color}"></circle>
          <text y="\${radius + 14}" text-anchor="middle">\${escapeHtml(shortLabel(node.name || node.path))}</text>
        </g>\`;
      }).join("");
    }

    function layoutNodes(nodes, edges) {
      const byLanguage = new Map();
      nodes.forEach((node) => {
        const language = node.external ? "External" : node.language;
        if (!byLanguage.has(language)) byLanguage.set(language, []);
        byLanguage.get(language).push(node);
      });

      const groups = [...byLanguage.entries()].sort((a, b) => b[1].length - a[1].length);
      const layout = new Map();
      const centerX = 0;
      const centerY = 0;
      const groupsCount = Math.max(1, groups.length);
      const edgeCount = new Map();
      edges.forEach((edge) => {
        edgeCount.set(edge.source, (edgeCount.get(edge.source) || 0) + 1);
        edgeCount.set(edge.target, (edgeCount.get(edge.target) || 0) + 1);
      });

      groups.forEach(([language, group], groupIndex) => {
        const angle = (Math.PI * 2 * groupIndex) / groupsCount - Math.PI / 2;
        const groupWeight = group.reduce((sum, node) => sum + Math.log10(node.score + 10), 0);
        const baseRadius = 190 + Math.min(420, Math.sqrt(groupWeight) * 8);
        group.sort((a, b) => (edgeCount.get(b.id) || 0) - (edgeCount.get(a.id) || 0) || b.score - a.score);
        group.forEach((node, index) => {
          const spread = ((index + 0.5) / group.length) * Math.PI * 1.6 - Math.PI * 0.8;
          const radial = baseRadius + ((stableHash(node.id) % 90) - 45);
          const x = centerX + Math.cos(angle) * radial + Math.cos(spread) * 90;
          const y = centerY + Math.sin(angle) * radial + Math.sin(spread) * 90;
          layout.set(node.id, { x, y });
        });
      });

      return layout;
    }

    function searchable(node) {
      return [node.id, node.name, node.path, node.language, ...(node.imports || []), ...(node.exports || [])].join(" ").toLowerCase();
    }

    function shortLabel(value) {
      const text = String(value || "");
      if (text.length <= 18) return text;
      return text.slice(0, 15) + "...";
    }

    function downloadSvg() {
      const clone = svg.cloneNode(true);
      clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");
      const blob = new Blob([new XMLSerializer().serializeToString(clone)], { type: "image/svg+xml;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = "\${escapeAttr(report.title)}-architecture.svg";
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
    }

    svg.addEventListener("click", (event) => {
      const node = event.target.closest && event.target.closest(".node");
      if (!node) return;
      selectedId = node.dataset.id;
      const data = nodes.find((item) => item.id === selectedId);
      if (!data) return;
      details.innerHTML = \`
        <h3>\${escapeHtml(data.path)}</h3>
        <p><b>\${escapeHtml(data.language)}</b> · \${data.loc.toLocaleString()} LOC · \${data.bytes.toLocaleString()} bytes</p>
        <p>Exports: \${data.exports.length ? data.exports.map(escapeHtml).join(", ") : "none detected"}</p>
        <p>Imports: \${data.imports.length ? data.imports.map(escapeHtml).join(", ") : "none detected"}</p>
        <p><code>\${escapeHtml(data.id)}</code></p>
      \`;
      renderGraph();
    });
  </script>
</body>
</html>
`;
}

function renderTree(node) {
  if (!node) return "";
  const className = node.type === "file" ? "file" : "";
  const label = node.path ? `<code>${escapeHtml(node.path)}</code>` : escapeHtml(node.name);
  const children = (node.children || []).slice(0, 16).map(renderTree).join("");
  return `<li class="${className}">${label}${children ? `<ul>${children}</ul>` : ""}</li>`;
}

module.exports = {
  renderHtml
};
